# -*- coding: utf-8 -*-
"""assignemt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1viHb_piXucvrjzPb8lqLZ9VemqnV-qzr
"""

from sympy import symbols, sin, cos, Matrix
from sympy.physics.mechanics import ReferenceFrame, Point, dynamicsymbols

omega = dynamicsymbols('omega')
m, l, b = symbols('m l b')

# Inertia of rods around G (mass center)

# referencing z axis

I_Gz = m*(b/3)**2 + m*(b+(b/3))**2 + (m*l**2)/4

# referencing y axis

I_Gy = (m*l**2)/4 + (2*m*b**2)

# referencing x axis

I_Gx = ( (m*l**2)/12 + m*(b/3)**2)*2 + ( (m*l**2)/12 + m*(2*b/3)**2 )

mt = [ [I_Gx , 0 , 0] , [ 0 , I_Gy , 0] , [ 0 , 0 , I_Gz]  ]

# Moment of inertia of the entire system about S*

I_matrix_S_about_Sstar = mt

